### ISSUE TITLE
Keyword ALTER PROCEDURE is not highlighted

### ISSUE THREAD

**Issue by ktaranov** [beau-witter/language-TSQL#3]
Hi, . Great thanks for awesome work. Could you help with syntax highlighting for `ALTER PROCEDURE` keyword? See example: https://github.com/ktaranov/sqlserver-kit/blob/master/Stored_Procedure/dbo.sp_BenchmarkTSQL.sql

More details here: https://github.com/github/linguist/issues/4622

**Comment by beau-witter** [comment]
Closed by https://github.com/beau-witter/language-TSQL/pull/4
